### ISSUE TITLE
Error installing Media Files addon with WP Migrate DB Pro 1.3b1

### ISSUE THREAD

**Issue by SideQuestDIY** [deliciousbrains/wp-migrate-db-pro-bugs#1]
Greetings team.

When trying to install the Media Files addon included in WP Migrate DB Pro 1.3b1 I get a strange error on my WP Engine server. I'm going to assume something about their security settings are not letting it pull the file. 

![wp-migrate-db-pro-error](https://f.cloud.github.com/assets/1471150/1640774/32135ff4-5842-11e3-9b3f-bf262c6eecba.jpg)

**Two things to note**
- Other plugins using the same technique of pulling for another server ( such as WooDojo ) work fine.  
- The install is works flawlessly on my localhost so the error seems to be limited to WP Engine at this point. 

I am happy to assist in solving this so if you need anything additional feel free to let me know.

**Comment by bradt** [comment]
Strange. We'll look into this and let you know if we need your help. I'll email you the zip so you can continue testing.

**Comment by SideQuestDIY** [comment]
Awesome, thank you. 

I checked my error logs and there doesn't seem to be anything. I did send a note to WP Engine to see if it was there system blocking the transfer, as I have had issues with their specific system before. I will update you when I hear back. 

**Edit**
The file you sent works great, it installed and pulled the files for the WP Engine server without an issue. So this issue seems to be limited to the add-on install.

**Comment by imagineutopia** [comment]
hi. I'm having the exact same issue. I'm trying to do a push pull from bluehost to bluehost and both sites when I go to install the media add on give me the same exact error as the original posters.

**Comment by theperfectwill** [comment]
I'm having the same problem. This happened with WPEngine and HostGator hosting. I did try everything out from local to local and the Media File Add-on worked beautifully! 

And I am just posting to stay updated. - Thanks.

**Comment by thorstone137** [comment]
I just submitted the same issue. I'm hosted at PagodaBox and their system only allows SFTP or Git so simply installing from the WP Dashboard in Production won't work for me.

I'm using DesktopServer/ServerPress which is a fork of Xammp-lite and attempt to install the addon locally I get the same issue submitted here. 

![2013-12-07_1227](https://f.cloud.github.com/assets/343876/1698882/472702be-5f6e-11e3-92e7-bbce4281c80a.png)

I have other WP plugins that install addons in the same fashion and I don't have the issue.

Is it possible to get a ZIPed file of the addon?

**Comment by bradt** [comment]
We're going to add a Download button next to the Install button in the next release for cases where installing isn't working or is not possible.

You should definitely be able to install the plugin locally though. It seems like there is a bug here that we still need to track down.

**Comment by theperfectwill** [comment]
Okay, thanks. I haven't tested more yet, but I will soon.

**Comment by phillcoxon** [comment]
I've had the same problem this morning trying to download the Media Addon. 

WP Migrate DB Pro 1.3 beta 2

Running on my own Cpanel/WHM server - no obvious causes but no issues with any other plugins.  

Do you have any debug info we can turn on to give more info?

**Comment by aprea** [comment]
I've tried to replicate this issue on a WP Engine box but was unable to.

To anyone experiencing this issue, would you be able to help us further diagnose this issue by providing WordPress admin credentials to the troublesome site?

An ideal situation would be that the site would be a development / staging site. This will allow me to do some more aggressive debugging without the worry of messing up the site.

If so, please email your credentials to nom@deliciousbrains.com

Thanks!

**Comment by phillcoxon** [comment]
@aprea - I've just emailed you login details to a dev site.

**Comment by aprea** [comment]
Thanks @getresults, got it. Checking it out now.

**Comment by aprea** [comment]
Hello gents, I've been working with @getresults on the issue and in his particular scenario the issue was caused by a plugin conflict.

The plugin in question was "WPMU DEV Dashboard".

If possible, is anyone else that is experiencing this problem able to disable their plugins and attempt the addon install process again? This will tell us if the problem is primarily caused by plugin conflicts or if it's something else.

Thanks!

**Comment by theperfectwill** [comment]
@aprea, I tried out the WPMUDev issues. For me it was a combination of\* WPMUDev's Dashboard and WPMUDev's "Ultimate Branding" plugin. Even though WPMUDev Dashboard was disabled, the media add-on wouldn't install until I deactivated the Ultimate Branding plugin. 

This was on local development, so that would explain now why installing the media add-on via localhost wouldn't work. 

I'm not sure if an add-on from Ultimate Branding is the individual problem yet, or Ultimate Branding itself. 
If it helps, in the Ultimate Branding plugin I use the following add-ons: 
Custom Footer Message, Custom Login Css, Custom Admin Css, Login Image, Hide The Dashboard Welcome and the
Remove Dashboard Widgets Add-ons.

I had a similar problem, now that I recall, with WPBakery's Visual Composer plugin but the opposite. Where the installation of WPMUDev's plugins would install but not activate via the WPMUDev dashboard. That has been since  though.
- Also, I would like to update that for some reason when trying everything over again, but with a new Dev site to sync that I had no problem using the Media Add-on and it pulling 856 media files from a HostGator site. This is in regard to the ajax error I was getting before when trying to connect.

**Comment by SideQuestDIY** [comment]
Interesting. I did get things working on WP Engine. For me it was a conflict with the **Github Plugin Search** plugin. 

A note for those trying to get this to work on WP Engine. If you are working on the live site WP Engine's caching system seems to cause issues with the install even if all plugins are disabled, you purge the cache, and reset file permissions. Copying the site to staging, disabling all plugins, installing the media addon works great.

**Comment by aprea** [comment]
hey @twittem, so the addon just outright will not work on WP Engines production servers because of their caching system? I had only done testing on their staging infrastructure and as you mentioned it appeared to be working there just fine

**Comment by SideQuestDIY** [comment]
@aprea Unfortunately, that seems to be the case. 

It's in interesting challenge as WordPress simply dies with no feedback. I have been working with WP Engine to see if there is a reason the errors still crop up after clearing the cache, of if there are errors logged on their end.

I will pass on anything of use I discover.

**Comment by aprea** [comment]
@twittem, I was doing some testing yesterday on my production WP Engine server and it appeared to be working for me.

One thing I was going to ask you to test is whether this is strictly related to the media addon or whether it's related to the database pulling part.

One way you can test this is to perform a pull but only select a really small table, e.g. wp_links

I have noticed some problem with the base plugin functionality on WP Engine, I've at times run into 502 bad gateway issues.

**Comment by SideQuestDIY** [comment]
@aprea, the base plugin works great and once installed the media addon works great too. 

The problem in production seems to only be when there was a conflicting plugin, in my case _Github Plugin Search_ and you disable it. It doesn't seem to actually be disabled in production and the error persists.

**Comment by aprea** [comment]
Oh right, so the only problem was that there was a conflicting plugin? Otherwise the plugin works just fine?
