### ISSUE TITLE
media files backup - extra letter in file name

### ISSUE THREAD

**Issue by mtcreations** [deliciousbrains/wp-migrate-db-pro-bugs#12]
just ran a test to pull from production to local, and the new media files came down with an extra letter (repeated) in front of each file name:
ggoogle-responsive-website-design.jpg  

odd bit of duck, eh?

if you need any other details (I don't want to throw stupid at you), let me know.

Mike T.

(happy user of v 1.2x!!!)

**Comment by aprea** [comment]
That's quite odd. I haven't been able to replicate this myself, nor have I seen anyone else report a similar issue just yet.

What do the attachments look like in your database (postmeta table)? Do they have the extra letter pretended?

**Comment by mtcreations** [comment]
postmeta looked normal. Once I removed the extra letter, images reappeared in blog.

**Comment by aprea** [comment]
Hmm strange, are you able to try something for me?

Open your browsers debugging console before you start the migration.

Once it has completed are you able to check the corresponding AJAX request and see what the POSTed variables are. See attached image as an example.

![ajax-console](https://f.cloud.github.com/assets/1527164/1721057/e24e4e3e-6214-11e3-887a-e0d040549d10.png)

**Comment by hchouhan** [comment]
@aprea 
Hi, I am facing same issue. The first character in the file name of the media files is duplicated.

I don't have firebug, but here is bit of a data from the console:

files_to_migrate: {saboc.jpg:610025, 1400.jpg:325642, yumeirodesign-jp.png:285216, 78.jpg:1132308,…}
78.jpg: 1132308
1400.jpg: 325642
blog-elegantthemes-builder.jpg: 136059
blog-elegantthemes-divi-300x250.jpg: 26594
blog-elegantthemes-divi-responsive.jpg: 177071
blog-elegantthemes-giveaway.jpg: 53783
institut-choiseul.jpg: 427161
macaw.jpg: 861199
rankcaptain.jpg: 691944
saboc.jpg: 610025
simple.jpg: 643083
stuff-and-nonsense.jpg: 558321
yumeirodesign-jp.png: 285216
remote_uploads_url: "http://flattrendz.com/wp-content/uploads"
total_size: 5928406

but after it copies, the file name in my local hosts folder is bblog-elegantthemes-builder.jpg instead of just "blog-elegantthemes-builder.jpg".

Tried it on 2 sites and faced same issue.

**Comment by aprea** [comment]
I know this is a little old now but I just wanted to let you guys know that this issue has been fixed and is scheduled to be released in the next update of the plugin.

**Comment by mtcreations** [comment]
wonderful, because I had disabled the media addon, as it was causing such
problems. look forward to fix!

On Mon, Jan 20, 2014 at 6:54 PM, Chris Aprea notifications@github.comwrote:

> I know this is a little old now but I just wanted to let you guys know
> that this issue has been fixed and it scheduled to be released in the next
> update of the plugin.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/deliciousbrains/wp-migrate-db-pro-bugs/issues/12#issuecomment-32808904
> .

## 

# 

Rescuing great businesses from bad websites since 1999
http://www.miketruesecreations.com
703 437 5034

**Comment by hchouhan** [comment]
@aprea great news. Thanks guys. Was manually downloading till now.
